### PR TITLE
new templates

### PR DESCRIPTION
**Pull request by gjbunyea**
\#86

# Description

Added new files to guide contribution and issues. Issue template geared toward bugs. Prep for collaboration phase.

# Change Log
Describe all changes made 

-`CONTRIBUTING.md` : boiler plate contribution guidelines. Modified to apply to our project
- `ISSUE_TEMPLATE.md` : Several important things most issues/bug reports should include - repro steps, expected results, context etc...

### CODE REVIEW

**Comment by zsmoore** [comment]
Looks good.  Since we are adding outside devs, should we include anything about requiring tests to validate new code?

**Comment by AlexPerri** [comment]
@zsmoore It's mentioned to write more tests if need be, Dave suggested we do that as well.

**Comment by zsmoore** [comment]
@AlexPerri @gjbunyea I know it is mentioned to write more but we currently have no structure for testing or guidelines even within our own team.  What would 'write more tests' entail?

**Comment by gjbunyea** [comment]
@zsmoore I have a testing PR i'm puttin in shortly.

**Pull request merged**
