### PR TITLE
Implement Editor Stepping

### PR DESCRIPTION
**Pull request by ghost**
\#65 #73 #67 

# Description
The code editor now highlights the line that is currently being stepped over. I also modified the Editor to make use of Ace's readonly mode feature.

# Change Log
`view/index.js` : Added a currentStep variable to the Interpreter state, which now gets passed into the Editor through the prop `highlightedLine`
`editor/index.js` : Swapped out the ternary statement to utilize the Ace's built-in readonly mode, highlight line based on whether we're in readonly mode and the prop value received from `view/index.js`

# Manual Test Steps
Write some code and try stepping over it. Make sure the line gets highlighted as intended.

### CODE REVIEW

**Review by gjbunyea — CHANGES_REQUESTED** [review]
**Requesting Change:** Doesn't accommodate for blank lines  - it should skip over them. 

**Optional Change:** Too many presses to restart - once I'm at the last line I have to press 'step' 3 times to restart - also it would be nice if 'step' changed to 'restart' or something when im at the last line.

**Review by zsmoore — CHANGES_REQUESTED** [review]
Looks good.

Personal opinion: i am fine with it still highlighting  blank lines since my interpret passes those lines back to code to visual it would be a little heavy to change that now.  Can do that after MVP.

If at the end of the step / run we can unhighlight the last line that would also be nice.

Also I would request, once we have started running or stepping we change the color of the run button to be red to indicate you can stop by clicking it.  Should just be a boolean chek.

Stretch: If there is a possibility to add a reset button to the UI tonight that would be great. not sure how hard that would be tho.

**Comment by gjbunyea** [comment]
My issue is that if I have a blank line, it gets highlights but is already running the next instruction. It then displaces all future highlights.

```
var x

x = 3
```
the last line will never be highlighted. It counts by num of instructions, not num of lines and which have instructions

**Comment by zsmoore** [comment]
The result of @gjbunyea 's bug is that the code editor does not send the interpreter an empty string with return if there is nothing on the line.  We need to inject newlines into the code editor in cases where there iss no test

**Comment by zsmoore** [comment]
@noahpoz 
NITPICK: Initial step puts us into pause red button instead of resume.
Also clicking on code editor while running will shift the highlight line until it refreshes.  Any way to disable clicking?

These are super picky, I am okay with letting these sslide in this PR

**Review by gjbunyea — APPROVED** [review]
I acknowledge @zsmoore's comments but am going to approve

**Review by zsmoore — APPROVED** [review]
Lets get this in.

**Pull request merged**
