### PR TITLE
Issue #25 - Finish frontend design

### PR DESCRIPTION
**Pull request by noahpoz**
Swapped out some semantic components and updated some styling. The code is in need of refactoring for the sake of robustness.

screen shot 2017-09-27 at 9 31 53 am

### CODE REVIEW

**Comment by gjbunyea** [comment]
@noahpoz please add some description to this PR (a screenshot would be nice as it's a design PR) 
and be sure to link the issue number. Also @AlexPerri is designated as your reviewer per [Team Contract](https://docs.google.com/document/d/1wUNw_FqKD53WnLlAYmNltjTNWTYE7EgAN7gOy6LrbfE/edit#heading=h.ck2ezdyvfhfa).

**Comment by zsmoore** [comment]
+1 on Greg's suggested changes

**Comment by noahpoz** [comment]
PR Update:
- Navbar restyling and addition of Ivy logo
- Page favicon
- Console styling

screen shot 2017-09-30 at 11 18 09 pm

**Comment by hartloff** [comment]
@gjbunyea Nice save on the tag!

**Pull request merged**
