### PR TITLE
Conditional Hacks

### PR DESCRIPTION
**Pull request by zsmoore**
#187 
#156 

# Description

Added functionality for conditional branching as long as the condition is wrapped in a variable.
Nesting conditions also works.

## Warning  
This code is very bad and will most likely be cleaned up / deleted after this 442 sprint.  
All of the new functionality is separated to a new file for that reason.  
Any new changes in interpret are flagged with a `// Hack` comment so we can clear it out easily after the class.

# Change Log

-`finish442Hacks.js` : All code added related to conditional branching
- `interpret.js`: Minimum possible changes to get functionality 

# Manual Test Steps
Test branching, remember what is in the conditional can only be a single variable

### CODE REVIEW

**Review by angushtlam — APPROVED** [review]
jk

**Review by angushtlam — CHANGES_REQUESTED** [review]
var z doesn't show up in visualizer. missing output?

```node
var x = 100;
var y = 90;

var a = 100 < 90;

if (a) {
    var z = 1000000;
} else {
    var z = "this should show up but doesn't";
}

var b = 100 > 90;

if (b) {
    var x = 1000000;
    
    if (a) {
        var x = 33213;
    } else {
        var z = "this should show up and does";
    }
    
    var d = false;
} else {
    var asmdkas = 'should not show up';
}

var c = false;

if (c) {
    var asmdkfdsafas = 'should not show up';
} else {
    var asmdkfdsafas = 'should show up and does';
}
```

**Comment by angushtlam** [comment]
Looks like it doesn't work with console logs too. Is it disregarding the whole branch? Also this one has a weird problem, the 3rd to last and 2nd to last blocks are exactly the same code but the second one doesn't work

```node
var x = 100;
var y = 90;

var a = x < y;
var b = x > y;
var c = true;
var d = false;

if (a) {
    console.log('no');
} else if (b) {
    console.log('yay it works');
} else if (c) {
    console.log('no');
}

if (a) {
    console.log('no');
}

if (b) {
    console.log('yay it works');
}

if (c) {
    console.log('yay it works');
}

if (a) {
    console.log('no');
} else if (d) {
    console.log('no');
} else {
    console.log('yay it works');
}

if (a) {
    console.log('no');
} else if (d) {
    console.log('no');
} else {
    console.log('should print');
}

if (a) {
    console.log('no');
} else {
    console.log('should print');
}
```

**Review by angushtlam — APPROVED** [review]

**Comment by angushtlam** [comment]
great fix, lg2m

**Review by ghost — CHANGES_REQUESTED** [review]
The `d = 4` assignment should be 2 scopes deeper than it is.

```
var a = true;

if (a) {
    var d = "1";
} else {
    var c = "nope";
}

var b = false;

if (b) {
    var c = "nope";
    
    if (a) {
        var c = "nope";
    }
} else {
    var d = "2";
    
    if (b) {
        var c = "nope";
    } else if (a) {
        var d = "3";
        
        if (a) {
            if (a) {
                if (b) {
                    var c = "nope";
                } else {
                    var d = "4";
                }
            }
        }
    }
}
```

**Review by ghost — APPROVED** [review]

**Pull request merged**
